# 錯誤與處理
---

+ ## **語法錯誤(Syntax Errors)**
    + **語法本身就錯誤，沒遵守python規定語法造成的錯誤**
    + **通常在編輯器裡面都會有語法錯誤的提示，所以通常是等不到真正執行程式時才發現**

+ ## **異常(Exceptions)**
    + **語法本身是對的，但還是報錯**
    + **這部分有很多，例如:分母不得為0，字串不能+數字...etc**
    + **有基本內建的異常，使用者也可以自定義異常**
    + **錯誤的類型也是個物件，父類都是Exception**   

+ ## 常見的報錯
    ```python
    # 屬性錯誤
    # import os
    # os.test
    """
    沒有這個屬性
    AttributeError: module 'os' has no attribute 'test'  
    """

    # import錯誤
    # import t
    """
    沒有這個module
    ModuleNotFoundError: No module named 't'
    """

    # 索引錯誤
    # a = [1]
    # print(a[1])
    """
    沒有這個值
    IndexError: list index out of range
    """

    # 字典的key值錯誤
    # a = {'a1': 1}
    # print(a['a2'])
    """
    沒有這個key
    KeyError: 'a2'
    """

    # 名稱錯誤
    # print(b)
    """
    該變數沒有定義
    NameError: name 'b' is not defined
    """

    # 分母為0錯誤
    # print(1/0)
    """
    分母不得為0
    ZeroDivisionError: division by zero
    """
    # 中斷錯誤
    # while True:
    #     pass
    """
    程式被中斷的錯誤
    KeyboardInterrupt
    """
    ```

+ ## 處理錯誤
  + **修正程式碼**
  + **預先對有可能發生錯誤的地方做處理**
 
  + ### 語法
    ```
    try:
        code block1
    except error_type:
        code block2
    except:
        code block3
    else:
        code block4
    finally:
        code block5
    ```
    PS: 
    1. error_type指得是報錯的類型字樣，例如AttributeError
    2. code block1有錯誤才會執行except，沒錯誤會執行else的code block4
    3. 不管code block1有沒有發生錯誤，都會執行finally的code block5
    4. 如果執行code block1發生錯誤的時候，會找該錯誤的類型是否是指定的error_type，若是則執行code block2，若否則執行code block3
    5. 注意:code block1裡面多行程式是執行到有錯誤的程式時才會往下跳，也就是該程式區塊在有問題的程式行之前的程式仍會執行

  + ### 範例
    ```python
    a = [10, 1, 5]

    try:
        b = [item for item in a if 100 % item == 0]
    except ZeroDivisionError:
        print('分母不得為0')
    except TypeError:
        print('分母要為數字')
    except:
        print('其它錯誤')
    else:
        print(b)
    finally:
        print('都會執行')
    ```

+ ## 抓取錯誤的資訊
  + ## 範例
    ```python
    import sys
    import traceback
    a = [10, 4, 3, 0, '10']
    try:
    b = [item for item in a if 100 % item == 0]
    except Exception as e:
    # 簡易版
    error_class = e.__class__.__name__  # 取得錯誤類型
    
    # 詳細版
    cl, exc, tb = sys.exc_info() #取得Call Stack
    lastCallStack = traceback.extract_tb(tb)[-1] #取得Call Stack最後一筆
    fileName = lastCallStack[0] #取得發生的檔案名稱
    lineNum = lastCallStack[1] #取得發生的行號
    funcName = lastCallStack[2] #取得發生的函數名稱
    
    """
    簡易版只有取得錯誤的類型以便用except來增加
    詳細版可以詳細印出發生問題的行數與function name
    """
    ```

+ ## 使用者自定義的錯誤
  + ### 範例
    ```python
    class MyException(Exception):
        pass


    try:
        raise MyException('自己創建的錯誤')
    except MyException as e:
        print(e)
    """
    raise為自行觸發報錯
    as 是把錯誤類型給實例化成e
    """
    ```

